# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_biaoding(object):
    def setupUi(self, biaoding):
        biaoding.setObjectName("biaoding")
        biaoding.resize(700, 397)
        biaoding.setMinimumSize(QtCore.QSize(700, 0))
        self.centralwidget = QtWidgets.QWidget(biaoding)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.RFRRradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.RFRRradioButton.setText("")
        self.RFRRradioButton.setObjectName("RFRRradioButton")
        self.horizontalLayout_6.addWidget(self.RFRRradioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.RFradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.RFradioButton.setText("")
        self.RFradioButton.setObjectName("RFradioButton")
        self.horizontalLayout_6.addWidget(self.RFradioButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.RRradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.RRradioButton.setText("")
        self.RRradioButton.setObjectName("RRradioButton")
        self.horizontalLayout_6.addWidget(self.RRradioButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.LFLRradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.LFLRradioButton.setText("")
        self.LFLRradioButton.setObjectName("LFLRradioButton")
        self.horizontalLayout_7.addWidget(self.LFLRradioButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.LFradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.LFradioButton.setText("")
        self.LFradioButton.setObjectName("LFradioButton")
        self.horizontalLayout_7.addWidget(self.LFradioButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.LRradioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.LRradioButton.setText("")
        self.LRradioButton.setObjectName("LRradioButton")
        self.horizontalLayout_7.addWidget(self.LRradioButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.Can1RFradioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Can1RFradioButton.setText("")
        self.Can1RFradioButton.setObjectName("Can1RFradioButton")
        self.horizontalLayout_8.addWidget(self.Can1RFradioButton)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.Can1LRradioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Can1LRradioButton.setText("")
        self.Can1LRradioButton.setObjectName("Can1LRradioButton")
        self.horizontalLayout_8.addWidget(self.Can1LRradioButton)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.Can1NoneradioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Can1NoneradioButton.setText("")
        self.Can1NoneradioButton.setObjectName("Can1NoneradioButton")
        self.horizontalLayout_8.addWidget(self.Can1NoneradioButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.Can2LFradioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.Can2LFradioButton.setText("")
        self.Can2LFradioButton.setObjectName("Can2LFradioButton")
        self.horizontalLayout_9.addWidget(self.Can2LFradioButton)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.Can2RRradioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.Can2RRradioButton.setText("")
        self.Can2RRradioButton.setObjectName("Can2RRradioButton")
        self.horizontalLayout_9.addWidget(self.Can2RRradioButton)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.Can2NoneradioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.Can2NoneradioButton.setText("")
        self.Can2NoneradioButton.setObjectName("Can2NoneradioButton")
        self.horizontalLayout_9.addWidget(self.Can2NoneradioButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.PatchlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PatchlineEdit.setObjectName("PatchlineEdit")
        self.horizontalLayout_10.addWidget(self.PatchlineEdit)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.SNlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SNlineEdit.setObjectName("SNlineEdit")
        self.horizontalLayout_10.addWidget(self.SNlineEdit)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.UserCodelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserCodelineEdit.setObjectName("UserCodelineEdit")
        self.horizontalLayout_10.addWidget(self.UserCodelineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SysCaliblabel = QtWidgets.QLabel(self.groupBox)
        self.SysCaliblabel.setObjectName("SysCaliblabel")
        self.horizontalLayout.addWidget(self.SysCaliblabel)
        self.SysCaliStart = QtWidgets.QPushButton(self.groupBox)
        self.SysCaliStart.setObjectName("SysCaliStart")
        self.horizontalLayout.addWidget(self.SysCaliStart)
        self.SysCaliResult = QtWidgets.QLineEdit(self.groupBox)
        self.SysCaliResult.setObjectName("SysCaliResult")
        self.horizontalLayout.addWidget(self.SysCaliResult)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AngleCaliblabel = QtWidgets.QLabel(self.groupBox_5)
        self.AngleCaliblabel.setObjectName("AngleCaliblabel")
        self.horizontalLayout_2.addWidget(self.AngleCaliblabel)
        self.AngleCaliStart = QtWidgets.QPushButton(self.groupBox_5)
        self.AngleCaliStart.setObjectName("AngleCaliStart")
        self.horizontalLayout_2.addWidget(self.AngleCaliStart)
        self.AngleResult = QtWidgets.QLineEdit(self.groupBox_5)
        self.AngleResult.setObjectName("AngleResult")
        self.horizontalLayout_2.addWidget(self.AngleResult)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Steplabel = QtWidgets.QLabel(self.groupBox_5)
        self.Steplabel.setObjectName("Steplabel")
        self.horizontalLayout_3.addWidget(self.Steplabel)
        self.SteplineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.SteplineEdit.setObjectName("SteplineEdit")
        self.horizontalLayout_3.addWidget(self.SteplineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 5, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.pushButtonEnd = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButtonEnd.setObjectName("pushButtonEnd")
        self.horizontalLayout_4.addWidget(self.pushButtonEnd)
        self.lineEditEnd = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditEnd.setObjectName("lineEditEnd")
        self.horizontalLayout_4.addWidget(self.lineEditEnd)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 6, 0, 1, 1)
        biaoding.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(biaoding)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menubar.setObjectName("menubar")
        biaoding.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(biaoding)
        self.statusbar.setObjectName("statusbar")
        biaoding.setStatusBar(self.statusbar)

        self.retranslateUi(biaoding)
        QtCore.QMetaObject.connectSlotsByName(biaoding)

    def retranslateUi(self, biaoding):
        _translate = QtCore.QCoreApplication.translate
        biaoding.setWindowTitle(_translate("biaoding", "标定"))
        self.groupBox_2.setTitle(_translate("biaoding", "安装类型："))
        self.label.setText(_translate("biaoding", "RF+RR"))
        self.label_3.setText(_translate("biaoding", "RF"))
        self.label_4.setText(_translate("biaoding", "RR"))
        self.label_5.setText(_translate("biaoding", "LF+LR"))
        self.label_6.setText(_translate("biaoding", "LF"))
        self.label_7.setText(_translate("biaoding", "LR"))
        self.groupBox_3.setTitle(_translate("biaoding", "CAN卡CAN1"))
        self.label_8.setText(_translate("biaoding", "雷达安装位置："))
        self.label_9.setText(_translate("biaoding", "右前"))
        self.label_10.setText(_translate("biaoding", "左后"))
        self.label_11.setText(_translate("biaoding", "无"))
        self.groupBox_4.setTitle(_translate("biaoding", "CAN卡CAN2"))
        self.label_12.setText(_translate("biaoding", "雷达安装位置："))
        self.label_13.setText(_translate("biaoding", "左前"))
        self.label_14.setText(_translate("biaoding", "右后"))
        self.label_15.setText(_translate("biaoding", "无"))
        self.label_16.setText(_translate("biaoding", "批次："))
        self.label_17.setText(_translate("biaoding", "SN号："))
        self.label_18.setText(_translate("biaoding", "客户编码："))
        self.groupBox.setTitle(_translate("biaoding", "系统标定："))
        self.SysCaliblabel.setText(_translate("biaoding", "系统标定："))
        self.SysCaliStart.setText(_translate("biaoding", "启动"))
        self.groupBox_5.setTitle(_translate("biaoding", "角度标定："))
        self.AngleCaliblabel.setText(_translate("biaoding", "角度标定："))
        self.AngleCaliStart.setText(_translate("biaoding", "启动"))
        self.Steplabel.setText(_translate("biaoding", "角度标定步骤:"))
        self.groupBox_6.setTitle(_translate("biaoding", "Type99:"))
        self.label_2.setText(_translate("biaoding", "Type99："))
        self.pushButtonEnd.setText(_translate("biaoding", "启动"))
